### PR TITLE
Create test env hierarchy.

### PR DESCRIPTION
**Pull request by ByzanTine**
Migrate some example tasks. Will write a new version of 4-room later, the current one lacks customizability and readability.

### CODE REVIEW

**Comment by bohanwu** [comment]
@ByzanTine

**Comment by bohanwu** [comment]
you don't need to add the test_env python files I believe

**Comment by ByzanTine** [comment]
What do you mean? Are you suggesting we don't need a similar hierarchy?

**Comment by bohanwu** [comment]
I meant i think it's best to keep the MLSH repo code untouched

**Comment by bohanwu** [comment]
I did pip install -e . too but the files didn't end up being added to my git commits

**Comment by ByzanTine** [comment]
I didn't change anything inside mlsh, just to fork a similar hierachry out.

**Comment by bohanwu** [comment]
oh i see, problem solved

**Pull request merged**
